networks:
  app-metafar-network-public:
    driver: bridge

volumes:
  sql_data:
    driver: local

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    networks:
      - app-metafar-network-public
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password12345" 
      ACCEPT_EULA: "Y" 
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  metafar.challenge.webapi:
    image: metafar.challenge.webapi:v1
    container_name: metafar.challenge.webapi
    depends_on:
      - sqlserver
    networks:
      - app-metafar-network-public
    ports:
        - '5000:8080'
    build:
      context: .
      dockerfile: Dockerfile
